#!/usr/bin/env bash
# apply.sh — reads services.json, writes /etc/caddy/Caddyfile, reloads Caddy
# Usage:
#   ./apply.sh            # apply current services.json
#   ./apply.sh --dry-run  # print what the Caddyfile would look like, don't apply

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICES_FILE="$SCRIPT_DIR/services.json"
CADDYFILE="/etc/caddy/Caddyfile"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is not installed. Run: sudo apt install jq"
  exit 1
fi

if [[ ! -f "$SERVICES_FILE" ]]; then
  echo "ERROR: services.json not found at $SERVICES_FILE"
  exit 1
fi

PI_IP=$(jq -r '.pi_ip' "$SERVICES_FILE")

CADDYFILE_CONTENT="# Auto-generated by apply.sh — edit services.json instead
# Generated: $(date)

"

while IFS= read -r line; do
  DOMAIN=$(echo "$line" | jq -r '.domain')
  PORT=$(echo "$line" | jq -r '.port')
  NOTE=$(echo "$line" | jq -r '.note // ""')

  CADDYFILE_CONTENT+="# ${NOTE}
${DOMAIN} {
    reverse_proxy localhost:${PORT}
}

"
done < <(jq -c '.services[]' "$SERVICES_FILE")

if $DRY_RUN; then
  echo "=== DRY RUN — would write to $CADDYFILE ==="
  echo "$CADDYFILE_CONTENT"
  echo "============================================"
  exit 0
fi

echo "$CADDYFILE_CONTENT" | sudo tee "$CADDYFILE" > /dev/null
echo "[apply.sh] Caddyfile written to $CADDYFILE"

if sudo caddy validate --config "$CADDYFILE" 2>&1; then
  sudo systemctl reload caddy
  echo "[apply.sh] Caddy reloaded successfully"
else
  echo "ERROR: Caddyfile validation failed — Caddy NOT reloaded"
  exit 1
fi

DNSMASQ_FILE="/etc/dnsmasq.d/pi-local.conf"
sudo tee "$DNSMASQ_FILE" > /dev/null <<EOF
# Auto-generated by apply.sh — $(date)
# Only explicitly listed domains resolve. All other .pi = NXDOMAIN.

local=/pi/
domain-needed
bogus-priv
server=8.8.8.8
server=1.1.1.1

$(jq -r --arg ip "$PI_IP" '.services[] | "address=/\(.domain)/\($ip)"' "$SERVICES_FILE")
EOF

echo "[apply.sh] dnsmasq config updated at $DNSMASQ_FILE"
sudo systemctl restart dnsmasq
echo "[apply.sh] dnsmasq restarted"
```

---

The generated `/etc/dnsmasq.d/pi-local.conf` will end up looking like:
```
local=/pi/
server=8.8.8.8
server=1.1.1.1

address=/reddit.pi/192.168.1.100
address=/wa.pi/192.168.1.100
address=/logger.pi/192.168.1.100