#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICES_FILE="$SCRIPT_DIR/services.json"
CADDYFILE="/etc/caddy/Caddyfile"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq not installed. Run: sudo apt install jq"
  exit 1
fi

PI_IP=$(jq -r '.pi_ip' "$SERVICES_FILE")

CADDY=""
while IFS= read -r line; do
  DOMAIN=$(echo "$line" | jq -r '.domain')
  PORT=$(echo "$line" | jq -r '.port')
  NOTE=$(echo "$line" | jq -r '.note // ""')
  CADDY+="# ${NOTE}
http://${DOMAIN} {
    reverse_proxy localhost:${PORT}
}

"
done < <(jq -c '.services[]' "$SERVICES_FILE")

if $DRY_RUN; then
  echo "=== Caddyfile ==="
  echo "$CADDY"
  exit 0
fi

echo "$CADDY" | sudo tee "$CADDYFILE" > /dev/null
echo "[apply] Caddyfile written"

if sudo caddy validate --config "$CADDYFILE" --adapter caddyfile 2>&1 | grep -q "Valid"; then
  sudo systemctl reload caddy
  echo "[apply] Caddy reloaded"
else
  echo "ERROR: Caddyfile invalid"
  exit 1
fi

DNSMASQ_ENTRIES=$(jq -r --arg ip "$PI_IP" '.services[] | "address=/\(.domain)/\($ip)"' "$SERVICES_FILE")

printf "# Auto-generated by apply.sh\n# Only listed domains resolve. All other .pi = NXDOMAIN.\nlocal=/pi/\nserver=8.8.8.8\nserver=1.1.1.1\n\n%s\n" "$DNSMASQ_ENTRIES" | sudo tee /etc/dnsmasq.d/pi-local.conf > /dev/null

echo "[apply] dnsmasq config written"
sudo systemctl restart dnsmasq
echo "[apply] dnsmasq restarted"

echo ""
echo "Active services:"
jq -r '.services[] | "  http://\(.domain) → localhost:\(.port)"' "$SERVICES_FILE"